extra-keys = [ \
  [ \
    {key: ESC}, \
    {macro: '<> LEFT', display: '<>'}, \
    {macro: '<', popup: '>', display: '><'}, \
    {key: BACKSLASH}, \
    {key: '='}, \
    {key: '_'}, \
    {key: '$'}, \
    {macro: '() LEFT', popup: '()', display: '()'}, \
    {macro: '{} LEFT', popup: '{}', display: '{}'}, \
    {macro: '[] LEFT', popup: '[]', display: '[]'}, \
    {key: DRAWER} \
  ], \
  [ \
    {key: TAB}, \
    {key: '&'}, \
    {key: ':'}, \
    {key: '|'}, \
    {key: '~'}, \
    {key: KEYBOARD}, \
    {key: '"'}, \
    {key: HOME}, \
    {key: UP}, \
    {key: END}, \
    {macro: '->', popup: '-', display: '->'} \
  ], \
  [ \
    {key: CTRL}, \
    {key: FN}, \
    {key: ALT}, \
    {key: SHIFT}, \
    {key: '*'}, \
    {key: '#'}, \
    {key: '@'}, \
    {key: LEFT}, \
    {key: DOWN}, \
    {key: RIGHT}, \
    {macro: '#include SPACE <> LEFT', popup: '#include <iostream>\n', display: '~INCL'} \
  ] \
]

terminal-cursor-style=bar
